version: '3.7'

services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - '${IP_HOST}:${POSTGRES_PORT}:5432'
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB_NAME:-ban-survey}